


var question={
  data: [
    {
      "answer": 64,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "<h5>CSS是层叠样式表。</h5> <p>层叠是指CSS应用一个样式可以有多个叠加</p> <p>样式表控制网络文件的外观和感觉。 </p> <h5>CSS和HTML通常是一块工作的</h5> <p>HTML整理页面结构。</p> <p> CSS定义如何显示HTML元素。</p>",
      "id": 18755,
      "label": "7.1.1.9",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "网页的脚本",
      "optionB": "存储网页的关键词",
      "optionC": "来控制网页文件的外观",
      "optionD": "定义网络文件的结构",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 1,
      "question": "CSS样式表用来干什么的?",
      "questionId": 910600,
      "falseCount": 1458798,
      "trueCount": 12655560,
      "wrongRate": 0.10335560427190525
    },
    {
      "answer": 32,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "<p>样式表控制网络文件的外观和感觉。 </p> ",
      "id": 18756,
      "label": "7.1.1.10",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "它让网页内容显示的更快",
      "optionB": "它让我们创建独一无二漂亮的网页",
      "optionC": "它可以创造网页和内容",
      "optionD": "它可以让网页更灵活",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 1,
      "question": "为什么用CSS?",
      "questionId": 910700,
      "falseCount": 1942266,
      "trueCount": 12380142,
      "wrongRate": 0.13561029681601028
    },
    {
      "answer": "style",
      "chapterId": 127,
      "difficulty": 1,
      "explain": "<p>为了使用内联样式，将样式属性添加到相关标记。</p><p>下面的例子演示了如何创建一个带有灰色背景和白色文本的段落：</p> <blockquote><textarea><p style='color:white; background-color:gray;'> 这是一个行内样式的案例</p></textarea></blockquote>", "id": 18758,
      "label": "7.1.1.12",
      "mediaHeight": 0,
      "mediaType": 1,
      "mediaWidth": 0,
      "optionA": "",
      "optionB": "",
      "optionC": "",
      "optionD": "",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 3,
      "question": "请输入设置内联样式的属性？",
      "questionId": 910900,
      "mediaContent": "http://file.open.jiakaobaodian.com/tiku/res/910900.jpg",
      "falseCount": 333184,
      "trueCount": 14157397,
      "wrongRate": 0.02299314292504904
    },
    {
      "answer": 224,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "接打手机或者发短信时不能双手握住方向盘，会影响正常驾驶操作，此时也要分心与对方交流，会分散注意力，此时发生紧急状况，肯定会反应不及。",
      "id": 18759,
      "label": "7.1.1.13",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "影响乘车人休息",
      "optionB": "分散驾驶注意力",
      "optionC": "影响正常驾驶操作",
      "optionD": "遇紧急情况反应不及",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "行车中驾驶人接打手机或发短信有什么危害？",
      "questionId": 911000,
      "falseCount": 1299618,
      "trueCount": 13098163,
      "wrongRate": 0.0902651596103594
    },
    {
      "answer": 240,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "常识题。可以有效避免驾驶疲劳有【连续驾驶不超过4小时】【用餐不宜过饱】【保持良好的睡眠】【餐后适当休息后驾车】的做法。",
      "id": 18760,
      "label": "7.1.1.14",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "连续驾驶不超过4小时",
      "optionB": "用餐不宜过饱",
      "optionC": "保持良好的睡眠",
      "optionD": "餐后适当休息后驾车",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "下列做法哪些可以有效避免驾驶疲劳？",
      "questionId": 911100,
      "falseCount": 1844335,
      "trueCount": 12347261,
      "wrongRate": 0.1299596606329549
    },
    {
      "answer": 240,
      "chapterId": 127,
      "difficulty": 4,
      "explain": "<p>驾驶汽车超速行驶使得反应距离延长；同时过快的车速使得两边的事物会比较模糊，视野变窄；太快的车速，由于惯性作用，就会加重事故后果以及制动距离延长等危害。</p>",
      "id": 18761,
      "label": "7.1.1.15",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "反应距离延长",
      "optionB": "视野变窄",
      "optionC": "加重事故后果",
      "optionD": "制动距离延长",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "驾驶汽车超速行驶有哪些危害？",
      "questionId": 911200,
      "falseCount": 4610807,
      "trueCount": 10063170,
      "wrongRate": 0.3142165889996965
    },
    {
      "answer": 96,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "弯道限速30公里/小时，以40公里/小时的速度行驶是超速。<br/>载货摩托车载客是非法载客。",
      "id": 18771,
      "label": "7.1.1.25",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "叶某驾驶与准驾车型不符的机动车",
      "optionB": "王某驾驶摩托车非法载客",
      "optionC": "叶某超速行驶",
      "optionD": "王某不按信号灯指示行驶",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "叶某驾驶中型厢式货车，行至陂头镇上汶线3公里加600米弯道路段时，以40公里/小时的速度与王某驾驶的乘载19人正三轮载货摩托车发生正面相撞，造成10人死亡、9人受伤。双方驾驶人的主要违法行为是什么？",
      "questionId": 912200,
      "falseCount": 1608820,
      "trueCount": 12978132,
      "wrongRate": 0.11029171824244023
    },
    {
      "answer": 48,
      "chapterId": 127,
      "difficulty": 4,
      "explain": "连续驾驶6小时属于疲劳驾驶。<br/>乘载57人（核载55人）客车超员。",
      "id": 18772,
      "label": "7.1.1.26",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "疲劳驾驶",
      "optionB": "客车超员",
      "optionC": "超速行驶",
      "optionD": "操作不当",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "某日19时，杨某驾驶大客车，乘载57人（核载55人），连续行驶至次日凌晨1时，在金城江区境内050国道3008公里加110米处，因机动车左前胎爆裂，造成12人死亡、22人受伤的特大交通事故。杨某的主要违法行为是什么？",
      "questionId": 912300,
      "falseCount": 3843647,
      "trueCount": 11141565,
      "wrongRate": 0.25649600419400137
    },
    {
      "answer": 160,
      "chapterId": 127,
      "difficulty": 1,
      "explain": "乘载74人(核载30人)，客车超员。<br/>弯道限速30公里/每小时，以每小时38公里的速度行驶，超速行驶。",
      "id": 18773,
      "label": "7.1.1.27",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "酒后驾驶",
      "optionB": "客车超员",
      "optionC": "疲劳驾驶",
      "optionD": "超速行驶",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "唐某驾驶一辆大客车，乘载74人（核载30人），以每小时38公里的速度，行至一连续下陡坡转弯路段时，机动车翻入路侧溪水内，造成17人死亡、57人受伤。唐某的主要违法行为是什么？",
      "questionId": 912400,
      "falseCount": 372167,
      "trueCount": 14513607,
      "wrongRate": 0.02500152158698634
    },
    {
      "answer": 144,
      "chapterId": 127,
      "difficulty": 3,
      "explain": "<p>行驶途中察觉制动装置有异常但未处理，属于驾驶具有安全隐患的机动车。<br/>时速为50公里（该路段限速40公里），超速行驶。</p><p>此题注意核载35人就是规定可以坐35人，实际乘坐了21人是没有超员的！</p>",
      "id": 18774,
      "label": "7.1.1.28",
      "mediaHeight": 0,
      "mediaType": 0,
      "mediaWidth": 0,
      "optionA": "超速行驶",
      "optionB": "疲劳驾驶",
      "optionC": "客车超员",
      "optionD": "驾驶具有安全隐患的机动车",
      "optionE": "",
      "optionF": "",
      "optionG": "",
      "optionH": "",
      "optionType": 2,
      "question": "李某驾驶一辆大客车，乘载21人（核载35人），行驶途中察觉制动装置有异常但未处理，行至双岛海湾大桥时时速为50公里（该路段限速40公里），因制动失灵坠入海中，造成13人死亡、8人受伤。李某的主要违法行为是什么？",
      "questionId": 912500,
      "falseCount": 2646365,
      "trueCount": 12866955,
      "wrongRate": 0.17058663135937374
    }
  ]
  
}